### ISSUE TITLE
'Check Answers' Button

### ISSUE THREAD

**Issue by rrwrds** [mnicholas26/arrowwords#20]
Validates all input on grid and makes sure if the user is correct -> dunno how i want to present this information yet (fill in wrong answers, just show whats wrong, only validate if all right etc)

**Comment by rrwrds** [comment]
Estimate: 0.25 days

**Comment by rrwrds** [comment]
First run: 
on click button checks inputted answers against real answers:

If correct then green 
else red

**Comment by mnicholas26** [comment]
see other closed issue, done but i do want to make a tweak, see newest batch of issues
