### ISSUE TITLE
UI investigation

### ISSUE THREAD

**Issue by rrwrds** [mnicholas26/arrowwords#39]
Look at other UIs, what is good bad ugly what would want ours to  look like.....

**Comment by rrwrds** [comment]
[rwdesigns.docx](https://github.com/mnicholas26/arrowwords/files/2617189/rwdesigns.docx)

**Comment by rrwrds** [comment]
https://docs.google.com/document/d/15wq3fdE7amxI-b4CVoqXuYjthrnQW9jB09PB7gI5si8/edit?usp=sharing

please add

**Comment by mnicholas26** [comment]
i think this is done now, we have our ui basically done for the time being, main changes will be small tweaks rather than large overhauls
